In [76]:
import numpy as np
import matplotlib.pyplot as plt
from numpy.linalg import inv

In [77]:
p = np.array([0, -4])
theta = np.pi / 3

q = np.array([*p, theta])

q

array([ 0.        , -4.        ,  1.04719755])

In [78]:
m = 3
r = 2
I = 0.5 * m * r**2

M = np.diag((m, m, I))

M

array([[3., 0., 0.],
       [0., 3., 0.],
       [0., 0., 6.]])

In [79]:
g = np.array([0.0, 0.0])
f = m*g
tau = 0

F = np.array([*f, tau])

F

array([0., 0., 0.])

In [80]:
L = 5

def C(q):
    x, y, theta = q
    return x**2 + y**2 - L**2

def J(q, q_dot):
    x, y, theta = q
    vx, vy, omega = q_dot
    return np.array([2*x*vx, 2*y*vy, 0])

In [81]:
dt = 0.1
b = 0

def lamb(q, q_dot):
    c = C(q)
    j = J(q, q_dot)
    
    lhs = j @ inv(M) @ j.T
    rhs = -(j @ (q_dot + inv(M) @ F * dt) + b)
    
    return rhs / lhs

In [82]:
def P_c(q, q_dot):
    j = J(q, q_dot)
    lambda_ = lamb(q, q_dot)
    
    return j.T * lambda_

In [83]:
p_dot = np.array([0, 1])
omega = np.pi / 2
q_dot = np.array([*p_dot, omega])

q_dot

array([0.        , 1.        , 1.57079633])

In [84]:
print(f"{q=}")
print(f"{q_dot=}")

c = C(q)
j = J(q, q_dot)
lambda_ = lamb(q, q_dot)
p_c = P_c(q, q_dot)
dv = inv(M) @ (F * dt + p_c)

print(f"{c=}")
print(f"{j=}")
print(f"{lambda_=}")
print(f"{p_c=}")
print(f"{dv=}")

q=array([ 0.        , -4.        ,  1.04719755])
q_dot=array([0.        , 1.        , 1.57079633])
c=np.float64(-9.0)
j=array([ 0., -8.,  0.])
lambda_=np.float64(0.375)
p_c=array([ 0., -3.,  0.])
dv=array([ 0., -1.,  0.])


In [85]:
for i in range(100):
    print(f"{i=}, {q=}, {q_dot=}")
    P = P_c(q, q_dot)
    q_dot = q_dot + inv(M) @ (F * dt + P)
    q = q + q_dot * dt

i=0, q=array([ 0.        , -4.        ,  1.04719755]), q_dot=array([0.        , 1.        , 1.57079633])
i=1, q=array([ 0.        , -4.        ,  1.20427718]), q_dot=array([0.        , 0.        , 1.57079633])
i=2, q=array([nan, nan, nan]), q_dot=array([nan, nan, nan])
i=3, q=array([nan, nan, nan]), q_dot=array([nan, nan, nan])
i=4, q=array([nan, nan, nan]), q_dot=array([nan, nan, nan])
i=5, q=array([nan, nan, nan]), q_dot=array([nan, nan, nan])
i=6, q=array([nan, nan, nan]), q_dot=array([nan, nan, nan])
i=7, q=array([nan, nan, nan]), q_dot=array([nan, nan, nan])
i=8, q=array([nan, nan, nan]), q_dot=array([nan, nan, nan])
i=9, q=array([nan, nan, nan]), q_dot=array([nan, nan, nan])
i=10, q=array([nan, nan, nan]), q_dot=array([nan, nan, nan])
i=11, q=array([nan, nan, nan]), q_dot=array([nan, nan, nan])
i=12, q=array([nan, nan, nan]), q_dot=array([nan, nan, nan])
i=13, q=array([nan, nan, nan]), q_dot=array([nan, nan, nan])
i=14, q=array([nan, nan, nan]), q_dot=array([nan, nan, nan])
i=15,

C:\Users\rhseung\AppData\Local\Temp\ipykernel_5864\2856721276.py:11: RuntimeWarning: invalid value encountered in scalar divide
  return rhs / lhs
